#
# softvis3d-sonarqube-it
# Copyright (C) 2020 Stefan Rinderle and Yvo Niedrich
# stefan@rinderle.info / yvo.niedrich@gmail.com
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02
#

FROM sonarqube:XX_SONARQUBE_VERSION_XX

ADD https://github.com/SonarSource/SonarTS/releases/download/1.1.0.1079/sonar-typescript-plugin-1.1.0.1079.jar /opt/sonarqube/extensions/downloads/

ADD ./XX_PLUGIN_FILENAME_XX /opt/sonarqube/extensions/downloads/XX_PLUGIN_FILENAME_XX