FROM sonarqube:XX_SONARQUBE_VERSION_XX

ADD https://github.com/Pablissimo/SonarTsPlugin/releases/download/v1.1.0/sonar-typescript-plugin-1.1.0.jar /opt/sonarqube/extensions/downloads/

ADD ./XX_PLUGIN_FILENAME_XX /opt/sonarqube/extensions/downloads/XX_PLUGIN_FILENAME_XX